import { PaintConfig } from "../typings/types";

export const paintConfig: PaintConfig = {
  Main: [
    "Main 1",
    "Main 2",
    "Main 3",
    "Main 4",
    "Main 5",
    "Main 6",
    "Main 7",
    "Main 8",
    "Main 10",
    "Main 11",
    "Main 12",
    "Main 13",
    "Main 14",
    "Main 15",
    "Main 16",
  ],
  Lawyer: [
    "Lawyer 1",
    "Lawyer 2",
    "Lawyer 3",
    "Main 8",
    "Main 10",
    "Main 11",
    "Main 12",
    "Main 13",
    "Main 14",
    "Main 15",
    "Main 16",
  ],
  "Fade To Five": [
    "Main 5",
    "Main 6",
    "Main 7",
    "Main 8",
    "Main 10",
    "Main 11",
    "Main 12",
    "Main 13",
    "Main 14",
    "Main 15",
    "Main 16",
  ],
  Abyss: [
    "Abyss 1",
    "Abyss 2",
    "Abyss 3",
    "Abyss 4",
    "Abyss 5",
    "Abyss 6",
    "Abyss 7",
    "Abyss 8",
    "Abyss 9",
    "Abyss 10",
  ],
  Spectrum: [
    "Spectrum 1",
    "Spectrum 2",
    "Spectrum 3",
    "Spectrum 4",
    "Spectrum 5",
    "Spectrum 6",
    "Spectrum 7",
    "Spectrum 6 (again)",
    "Spectrum 8",
    "Spectrum 9",
    "Spectrum 10",
    "Spectrum 11",
    "Spectrum 12",
  ],
};
